# Generated by Django 5.1.6 on 2025-03-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_video_user_alter_comment_user_alter_like_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='../vidifymedia'),
        ),
    ]
