# Generated by Django 5.1.6 on 2025-03-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_video_video_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='preview',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
